"""Allow order without employee

Revision ID: a9704255b29c
Revises: 16912ccd4b5c
Create Date: 2025-07-12 12:09:18.233958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9704255b29c'
down_revision: Union[str, None] = '16912ccd4b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column('id_employee', existing_type=sa.String(length=100), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column('id_employee', existing_type=sa.String(length=100), nullable=False)
    # ### end Alembic commands ###
