name: Tech Challenger CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGION_DEFAULT: "us-east-1"
  AWS_ECR_REGISTRY: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com"
  PROJECT_NAME: "soattc-order-app"

jobs:
  build:
    name: Build and Cache Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry dependencies
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install --with test --sync
  
  run_sonarqube:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: SonarSource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test:
    name: Run Tests in Parallel
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Restore Cached Dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Run Tests in Parallel
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          export ENV=test
          poetry run pytest --cov=src --numprocesses auto --dist loadfile --max-worker-restart 0

      - name: Generate Coverage Report
        run: |
          poetry run coverage report --omit=tests/*
          poetry run coverage xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 7  
  
  deploy_db:
    name: Deploy Database
    needs: [run_sonarqube, test]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ./terraform/db
        run: terraform init
      
      - name: Terraform Plan (PR)
        if: github.event_name == 'pull_request'
        working-directory: ./terraform/db
        run: terraform plan -var="eks_sg_id=sg-mockid123456789"
      
      - name: Create tfvars file
        working-directory: ./terraform/db
        run: |
          cat <<EOF > secrets.auto.tfvars
          db_username = "${{ secrets.DB_USERNAME }}"
          db_password = "${{ secrets.DB_PASSWORD }}"
          EOF

      - name: Select production workspace
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform/db
        run: terraform workspace new prod || terraform workspace select prod

      - name: Terraform Plan (Main)
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        working-directory: ./terraform/db
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform/db
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
  
  deploy_app:
    name: Deploy App
    needs: deploy_db
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.REGION_DEFAULT }} | docker login --username AWS --password-stdin ${{ env.AWS_ECR_REGISTRY }}

      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: build-image
        run: |
          # Build and push Docker image
          docker build --no-cache -t soattc-order-app:latest .
          docker tag soattc-order-app:latest ${{ env.AWS_ECR_REGISTRY }}/${{ env.PROJECT_NAME }}:latest
          docker push ${{ env.AWS_ECR_REGISTRY }}/${{ env.PROJECT_NAME }}:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ./terraform/app
        run: terraform init

      - name: Copy mocks if not in main branch
        if: github.ref != 'refs/heads/main'
        run: |
          cp terraform/mock/mock_rds_outputs.tfstate terraform/app/
          cp terraform/mock/mock_eks_outputs.tfstate terraform/app/
      
      - name: Select production workspace
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform/app
        run: terraform workspace new prod || terraform workspace select prod
      
      - name: Create tfvars file
        working-directory: ./terraform/app
        run: |
          cat <<EOF > secrets.auto.tfvars
          db_username = "${{ secrets.DB_USERNAME }}"
          db_password = "${{ secrets.DB_PASSWORD }}"
          secret_key = "${{ secrets.SECRET_KEY }}"
          order_microservice_api_key = "${{ secrets.ORDER_MICROSERVICE_API_KEY }}"
          payment_service_api_key = "${{ secrets.PAYMENT_SERVICE_API_KEY }}"
          payment_service_url = "${{ secrets.PAYMENT_SERVICE_URL }}"
          payment_notification_url = "${{ secrets.PAYMENT_NOTIFICATION_URL }}"
          stock_microservice_url = "${{ secrets.STOCK_MICROSERVICE_URL }}"
          stock_microservice_api_key = "${{ secrets.STOCK_MICROSERVICE_API_KEY }}"
          EOF

      # Terraform Plan (PR)
      - name: Terraform Plan
        working-directory: ./terraform/app
        run: terraform plan || true
        if: github.ref != 'refs/heads/main'

      # Terraform Plan (Main)
      - name: Terraform Plan
        working-directory: ./terraform/app
        run: terraform plan
        if: github.ref == 'refs/heads/main'

      - name: Terraform Apply
        working-directory: ./terraform/app
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve